### ISSUE TITLE
Dedicated Server Crash.

### ISSUE THREAD

**Issue by Dominance** [nflantier/FinalSFA#1]
Happens on startup.

http://pastebin.com/HmihBMTC

From what I can tell. Client only side stuff mixed in.

**Comment by nflantier** [comment]
Ok thanks you ! i totally forgot to debug server side :) ! i just finish fixing it, it should work properly now ! version 1.1.1 on curse.

**Comment by Dominance** [comment]
Works great bud thanks a lot!
