### ISSUE TITLE
Another server crash

### ISSUE THREAD

**Issue by Dominance** [nflantier/FinalSFA#2]
Havent been able to replicate this in SSP. 
http://pastebin.com/xaGPPs92

**Comment by nflantier** [comment]
fixed in version 1.1.2

**Comment by Dominance** [comment]
Seems to work great thanks again for the quick fix! A request to have a config option to toggle on/off the book spawning with the player at start would also be amazing!

**Comment by nflantier** [comment]
its comming in the next version m8 ;) i dont release it now because i added some new stuff
