### ISSUE TITLE
Heres another!

### ISSUE THREAD

**Issue by Dominance** [nflantier/FinalSFA#3]
Not exactly sure how these players made this possible as none of them had a item/block from SF. http://pastebin.com/zyzudpWT

**Comment by nflantier** [comment]
i wil upload a new version where i added some safety check . Is the bug constantly make the game crash ?

**Comment by Dominance** [comment]
For the client yes. I do think this is a cauldron only issue and only happens on a kcauldron SMP. I have not been able to replicate it after tossing the shield about 5000 times on my test server or in SSP. Thanks again for the quick update bud I really appreciate it!

**Comment by Dominance** [comment]
ok seems to of fixed the issue with the crash. I am having another issue how ever with a server that is running the mod. http://i.imgur.com/WAFCSjb.png Not sure if this is intended to tick or not ?

**Comment by nflantier** [comment]
yes it s intended to spawn custom particle with custom render distance, what tool did you use in that screenshot?

**Comment by Dominance** [comment]
Sorry for the late response. That I believe was done via Opis. I have profiled with jvisual and others with similar results. Also the pillars iirc seem to be showing up on profilers as well. Would it be possible to give these server owners a config option to turn some of that off so they stop yelling at me :)

**Comment by nflantier** [comment]
the pillars iirc ? what do you mean by that?

**Comment by Dominance** [comment]
Sorry IIRC = If I remember correctly. I had to ask that same question about 2 weeks ago.

**Comment by Dominance** [comment]
Here is a few more profiles from a active server http://i.imgur.com/HYqcIw6.png http://i.imgur.com/jQQX67x.png. This is also limiting there tick rate at -4x As you can see for a server its a major issue. Single player not so much at all.

**Comment by nflantier** [comment]
ahh ok ;) i have another idea for the ores but what about pillars ?

**Comment by Dominance** [comment]
I really need to start subscribing to github. Yeah talked with the server that was a mistake on my part sorry nflantier.

**Comment by nflantier** [comment]
ok np ! i will release soon a new version where ores doesnt use tile entities !

**Comment by Dominance** [comment]
Thanks a lot! I do admit I think the sparks are really cool but the servers hate it :)
